name: SonarCloud

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Ejecutar análisis con Gradle y SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey=Niny_Parra_sitewhere \
            -Dsonar.organization=Niny_Parra \
            -Dsonar.host.url=https://sonarcloud.io